version: '2'
volumes:
  gitlab-app-data:
    driver: ${volumedriver}
    {{- if eq .Values.volumedriver "rancher-ebs" }}
    driver_opts:
      size: ${gitlab_data_volume_size}
      volumeType: gp2
    {{- end}}
  gitlab-log-data:
    driver: ${volumedriver}
    {{- if eq .Values.volumedriver "rancher-ebs" }}
    driver_opts:
      size: 10
      volumeType: gp2
    {{- end}}
  gitlab-conf-files:
    driver: ${volumedriver}
    {{- if eq .Values.volumedriver "rancher-ebs" }}
    driver_opts:
      size: 1
      volumeType: gp2
    {{- end}}
  letsencrypt:
    driver_opts:
      size: '1'
    driver: rancher-ebs

services:
  gitlab-server:
    ports:
      - ${ssh_port}:22/tcp
      - ${http_port}:${http_port}/tcp
      - ${https_port}:${https_port}/tcp
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: letsencrypt
    image: gitlab/gitlab-ce:9.4.5-ce.0
    volumes:
      - gitlab-app-data:/var/opt/gitlab
      - gitlab-log-data:/var/log/gitlab
      - gitlab-conf-files:/etc/gitlab
    volumes_from:
      - letsencrypt
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['lfs_enabled'] = true
        {{- if eq .Values.gitlab_omnipus_prefix "http://" }}
        {{- if eq .Values.http_port "80" }}
        external_url '${gitlab_omnipus_prefix}${gitlab_hostname}'
        registry_external_url '${gitlab_omnipus_prefix}${registry_gitlab_hostname}'
        {{ else }}
        external_url '${gitlab_omnipus_prefix}${gitlab_hostname}:${http_port}'
        registry_external_url '${gitlab_omnipus_prefix}${registry_gitlab_hostname}:${http_port}'
        {{- end}}
        {{- else }}
        {{- if eq .Values.https_port "443" }}
        external_url '${gitlab_omnipus_prefix}${gitlab_hostname}'
        registry_external_url '${gitlab_omnipus_prefix}${registry_gitlab_hostname}'
        {{ else }}
        external_url '${gitlab_omnipus_prefix}${gitlab_hostname}:${https_port}'
        registry_external_url '${gitlab_omnipus_prefix}${registry_gitlab_hostname}:${https_port}'
        {{- end}}        
        {{- end}}
        {{- if ne .Values.ssh_port "22" }}
        gitlab_rails['gitlab_shell_ssh_port'] = ${ssh_port}
        {{- end}}
        nginx['ssl_certificate'] = '/etc/letsencrypt/production/certs/gitlab/fullchain.pem'
        nginx['ssl_certificate_key'] = '/etc/letsencrypt/production/certs/gitlab/privkey.pem'
  letsencrypt:
    image: janeczku/rancher-letsencrypt:v0.5.0
    environment:
      API_VERSION: Production
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      CERT_NAME: gitlab
      DOMAINS: ${gitlab_hostname}, ${registry_gitlab_hostname}
      EMAIL: ${EMAIL}
      EULA: 'Yes'
      PROVIDER: Route53
      PUBLIC_KEY_TYPE: RSA-2048
      RENEWAL_TIME: '12'
    volumes:
    - /var/lib/rancher:/var/lib/rancher
    - letsencrypt:/etc/letsencrypt
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
